#pragma once
#ifndef DS_MODEL_AUTOGENERATED_Table_Name
#define DS_MODEL_AUTOGENERATED_Table_Name

#include <ds/data/resource.h>
#include <memory>
#include <vector>
#include <cinder/Vector.h>

namespace ds {
namespace model{
/**
* \class ds::model::TableName
*			Auto-generated data model for TableName
*/
class TableNameRef {
public:

	TableNameRef();

	const int				getInt() const;
	const unsigned int		getUint() const;
	const float				getFloat() const;
	const std::string&		getString() const;
	const ds::Resource&		getResource() const;

	TableNameRef&			setInt(const int ColumnName);
	TableNameRef&			setUint(const unsigned int ColumnName);
	TableNameRef&			setFloat(const float ColumnName);
	TableNameRef&			setString(const std::string& ColumnName);
	TableNameRef&			setResource(const ds::Resource& ColumnName);

	void COLUMN_DATA();

private:
	class Data;
	std::shared_ptr<Data>	mData;
};

} // namespace model
} // namespace ds

#endif

