// Copyright (c) 2025 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the make_api_versions_header.py tool. Versions
// are managed using the version_manager.py tool. For usage details see
// https://bitbucket.org/chromiumembedded/cef/wiki/ApiVersioning.md
//

#ifndef CEF_INCLUDE_CEF_API_VERSIONS_H_
#define CEF_INCLUDE_CEF_API_VERSIONS_H_

#include "include/base/cef_build.h"

// Added February 17, 2025.
#define CEF_API_VERSION_13300 13300
#define CEF_API_HASH_13300_UNIVERSAL "c1a7d47be6fc130795366a1627573aa8eba1106f"
#if defined(OS_WIN)
#define CEF_API_HASH_13300_PLATFORM "0efb201c9e981c4513aeea04f9f2f8041ee9ce1f"
#elif defined(OS_MAC)
#define CEF_API_HASH_13300_PLATFORM "3891d2358697f15e046afc65fefd7019d888817a"
#elif defined(OS_LINUX)
#define CEF_API_HASH_13300_PLATFORM "87d31692cf1ff1f0f2445dd026dcc0aeb02c5786"
#endif

// Added February 17, 2025.
#define CEF_API_VERSION_13301 13301
#define CEF_API_HASH_13301_UNIVERSAL "892e654249acc7360f8aca4ee77da896753b87b8"
#if defined(OS_WIN)
#define CEF_API_HASH_13301_PLATFORM "cf9fbb7aa6778fedce78b8557044f219f2b5ba0b"
#elif defined(OS_MAC)
#define CEF_API_HASH_13301_PLATFORM "d3ec7d79adbde067590ab1bfff1f30dd8b06546a"
#elif defined(OS_LINUX)
#define CEF_API_HASH_13301_PLATFORM "747f624e5059839e6a7d385de7997d45bbd42184"
#endif

// Added February 17, 2025.
#define CEF_API_VERSION_13302 13302
#define CEF_API_HASH_13302_UNIVERSAL "acab8df1244923f1f80b18214e73c276a553ded6"
#if defined(OS_WIN)
#define CEF_API_HASH_13302_PLATFORM "c4b5a65478bc1a679f4a47ba5ff6899e5c3d8761"
#elif defined(OS_MAC)
#define CEF_API_HASH_13302_PLATFORM "cfe09351db37aa275613c27145fe622d9c28d4cc"
#elif defined(OS_LINUX)
#define CEF_API_HASH_13302_PLATFORM "ae4ab1c52ad951d37e6397db9f4e0ab0ce5044cf"
#endif

// Added February 17, 2025.
#define CEF_API_VERSION_13303 13303
#define CEF_API_HASH_13303_UNIVERSAL "128210b71e3f621cb6d2c4b05c6d0408a4547f2f"
#if defined(OS_WIN)
#define CEF_API_HASH_13303_PLATFORM "5a22d42c3e6294eb4ee2424053eebdeae3027899"
#elif defined(OS_MAC)
#define CEF_API_HASH_13303_PLATFORM "8085a0f62f15946343c63788300e5c2b422b3301"
#elif defined(OS_LINUX)
#define CEF_API_HASH_13303_PLATFORM "2683698b779f11bba19f4051e3760fe327a1c8b2"
#endif

// Added February 17, 2025.
#define CEF_API_VERSION_13304 13304
#define CEF_API_HASH_13304_UNIVERSAL "131b720865dd5c54c72041c0fbfb7c9bbfee8e0b"
#if defined(OS_WIN)
#define CEF_API_HASH_13304_PLATFORM "979b48138012378192dac7ee972fa731e9c0dae9"
#elif defined(OS_MAC)
#define CEF_API_HASH_13304_PLATFORM "32af7e8f8828b04cf2908de9857940faa54deb8a"
#elif defined(OS_LINUX)
#define CEF_API_HASH_13304_PLATFORM "c709233cd071e0d715eb10ceec4c5aea805df997"
#endif

// Added February 19, 2025.
#define CEF_API_VERSION_13400 13400
#define CEF_API_HASH_13400_UNIVERSAL "65de718ba0e0693dfc3b26e7e6a4814bbeeb10be"
#if defined(OS_WIN)
#define CEF_API_HASH_13400_PLATFORM "afe73f64f156154ff5b099c36186cbc03136172d"
#elif defined(OS_MAC)
#define CEF_API_HASH_13400_PLATFORM "7a20d0f7dc388406111461d6b1addd329b4be567"
#elif defined(OS_LINUX)
#define CEF_API_HASH_13400_PLATFORM "342696aa818bc9a512cc965ed4c19ba705d2c839"
#endif

// Next version last updated February 21, 2025.
#define CEF_API_VERSION_999998 999998
#define CEF_API_HASH_999998_UNIVERSAL "65de718ba0e0693dfc3b26e7e6a4814bbeeb10be"
#if defined(OS_WIN)
#define CEF_API_HASH_999998_PLATFORM "afe73f64f156154ff5b099c36186cbc03136172d"
#elif defined(OS_MAC)
#define CEF_API_HASH_999998_PLATFORM "7a20d0f7dc388406111461d6b1addd329b4be567"
#elif defined(OS_LINUX)
#define CEF_API_HASH_999998_PLATFORM "342696aa818bc9a512cc965ed4c19ba705d2c839"
#endif

// Experimental version last updated February 21, 2025.
#define CEF_API_VERSION_999999 999999
#define CEF_API_HASH_999999_UNIVERSAL "219c3a8b455b6db607fc24704d511ad821072ddb"
#if defined(OS_WIN)
#define CEF_API_HASH_999999_PLATFORM "19a9ec159c9927892db0dddd5170f20216218452"
#elif defined(OS_MAC)
#define CEF_API_HASH_999999_PLATFORM "a2223aba5ca284070b8b6cc7dfa03c856bf1fbf6"
#elif defined(OS_LINUX)
#define CEF_API_HASH_999999_PLATFORM "45597bbae3187c4d81c537d7686aad8e9be82847"
#endif

// Oldest supported CEF version.
#define CEF_API_VERSION_MIN CEF_API_VERSION_13300

// Newest supported CEF version.
#define CEF_API_VERSION_LAST CEF_API_VERSION_13400

#endif  // CEF_INCLUDE_CEF_API_VERSIONS_H_
