#pragma once
#ifndef DS_UI_TEXT_H
#define DS_UI_TEXT_H
#include <cinder/gl/Texture.h>
#include <cinder/gl/TextureFont.h>
#include <cinder/Text.h>
#include <cinder/Font.h>
#include "ds/ui/sprite/sprite.h"
#include "ds/ui/sprite/text_layout.h"

namespace ds {
namespace ui {

/**
 * \class ds::ui::Text
 * A sprite for displaying text.  All layouts are generated by a layout
 * function.  See text_layout for all possible functions, or write your own.
 * Note that some functions require additional properties not on the sprite
 * (for example, spacing between lines, for multi-line layouts), in which
 * case the function is typically generated by an additional object responsible
 * for storing the info.
 */
class Text: public Sprite
{
    public:
        Text(SpriteEngine&);
        ~Text();
        Text&                     setResizeToText(const bool = true);
        Text&                     setFont(const std::string& filename, const float fontSize);
        void                      setSize( float width, float height );
        void                      setSize( float width, float height, float depth );
        virtual float             getWidth() const;
        virtual float             getHeight() const;
        void                      setAlignment( int alignment );
        Text&                     setBorder(const ci::Rectf&);
        virtual void              updateServer(const UpdateParams&);
        void                      drawLocalClient();
        Text&                     setText( const std::string &text );
        std::string               getText() const;

        // Set a function for translating a string into a layout object.
        Text&                     setLayoutFunction(const TextLayout::MAKE_FUNC&);

    private:
        typedef Sprite inherited;

        void                      makeLayout();
        // Only used when ResizeToText is on
        void                      calculateFrame();

        ci::gl::TextureFontRef    mTextureFont;
        ci::gl::TextureFont::DrawOptions
                                  mDrawOptions;
        
        float                     mFontSize;
        std::string               mTextString;
        ci::Rectf                 mBorder;

        // When on, my width and height changes automatically to match my text
        bool                      mResizeToText;
        TextLayout                mLayout;
        bool                      mNeedsLayout;
        TextLayout::MAKE_FUNC     mLayoutFunc;

        // When true, display the whole sprite area.
        const bool                mDebugShowFrame;

        // Initialization
    public:
        static void                     installAsServer(ds::BlobRegistry&);
        static void                     installAsClient(ds::BlobRegistry&);
};

} // namespace ui
} // namespace ds

#endif//DS_UI_TEXT_H
