# Recursively finds directories that contain a CMakeLists.txt (ex. examples and tests)
macro( findCMakeDirs RESULT_PATHS BASE_PATH SKIP_PATHS )
	file( GLOB results "${BASE_PATH}/*"  )
	foreach( f ${results} )
		if( EXISTS "${f}/CMakeLists.txt" AND NOT IS_DIRECTORY "${f}/CMakeLists.txt" )
			ds_log_i( "---- [findCMakeDirs] Found file: ${f}/CMakeLists.txt" )

			set( shouldSkip FALSE )
			foreach( skip ${SKIP_PATHS} )
				if( f MATCHES ".*${skip}" )
					ds_log_i( "---- [findCMakeDirs] skipping path: ${f}" )
					set( shouldSkip TRUE )
					break()
				endif()
			endforeach()
			if( shouldSkip )
				continue()
			endif()

			#get_filename_component( parentDir ${f} DIRECTORY )
			set( ${RESULT_PATHS} ${${RESULT_PATHS}} ${f} )
		endif()
	endforeach()
endmacro( findCMakeDirs RESULT_PATHS BASE_PATH )
