# This file is used to specify sources that become part of the libds-cinder-platform binary

list( APPEND DS_CINDER_SRC_FILES
	#${ROOT_PATH}/src/stdafx.cpp
	${ROOT_PATH}/src/ds/util/date_util.cpp
	${ROOT_PATH}/src/ds/util/image_meta_data.cpp		# Need <intrin.h>
	${ROOT_PATH}/src/ds/util/file_meta_data.cpp
	${ROOT_PATH}/src/ds/util/color_util.cpp				# sprintf_s (windows)
	${ROOT_PATH}/src/ds/util/string_util.cpp
	${ROOT_PATH}/src/ds/util/idle_timer.cpp
	${ROOT_PATH}/src/ds/util/exif.cpp
	${ROOT_PATH}/src/ds/util/bit_mask.cpp
	${ROOT_PATH}/src/ds/arc/arc_input.cpp
	${ROOT_PATH}/src/ds/arc/arc.cpp
	${ROOT_PATH}/src/ds/arc/arc_color_array.cpp
	${ROOT_PATH}/src/ds/arc/arc_chain.cpp
	${ROOT_PATH}/src/ds/arc/arc_render_circle.cpp
	${ROOT_PATH}/src/ds/arc/arc_pow.cpp
	${ROOT_PATH}/src/ds/arc/arc_map.cpp
	${ROOT_PATH}/src/ds/arc/arc_layer.cpp
	${ROOT_PATH}/src/ds/arc/arc_io.cpp
	${ROOT_PATH}/src/ds/gl/uniform.cpp
	${ROOT_PATH}/src/ds/network/http_client.cpp		# error: invalid initialization of non-const reference of type ‘std::unique_ptr<ds::WorkRequest>&’ from an rvalue of type ‘std::unique_ptr<ds::WorkRequest>’
	${ROOT_PATH}/src/ds/network/node_watcher.cpp
	${ROOT_PATH}/src/ds/network/packet_chunker.cpp
	${ROOT_PATH}/src/ds/network/tcp_client.cpp
	${ROOT_PATH}/src/ds/network/tcp_server.cpp
	${ROOT_PATH}/src/ds/network/tcp_socket_sender.cpp
	${ROOT_PATH}/src/ds/network/udp_connection.cpp
	${ROOT_PATH}/src/ds/network/single_udp_receiver.cpp
	${ROOT_PATH}/src/ds/network/network_info.cpp		# Uses winsock2 apis
	${ROOT_PATH}/src/ds/time/timer.cpp
	${ROOT_PATH}/src/ds/thread/work_request.cpp
	${ROOT_PATH}/src/ds/thread/work_manager.cpp
	${ROOT_PATH}/src/ds/thread/gl_thread.cpp			# Uses win32 and WGL APIs
	${ROOT_PATH}/src/ds/thread/runnable_client.cpp		# error: invalid initialization of non-const reference of type ‘std::unique_ptr<ds::WorkRequest>&’ from an rvalue of type ‘std::unique_ptr<ds::WorkRequest>’
	${ROOT_PATH}/src/ds/thread/work_client.cpp
	#${ROOT_PATH}/src/ds/storage/directory_watcher_win32.cpp	# Uses win32 apis
	${ROOT_PATH}/src/ds/storage/persistent_cache.cpp
	${ROOT_PATH}/src/ds/storage/directory_watcher.cpp
	${ROOT_PATH}/src/ds/query/query_result.cpp			
	${ROOT_PATH}/src/ds/query/sql_query_result_builder.cpp
	${ROOT_PATH}/src/ds/query/query_result_builder.cpp
	${ROOT_PATH}/src/ds/query/sql_database.cpp
	${ROOT_PATH}/src/ds/query/query_client.cpp			# error: invalid initialization of non-const reference of type ‘std::unique_ptr<ds::WorkRequest>&’ from an rvalue of type ‘std::unique_ptr<ds::WorkRequest>’
	${ROOT_PATH}/src/ds/query/query_result_editor.cpp
	${ROOT_PATH}/src/ds/app/event_client.cpp
	${ROOT_PATH}/src/ds/app/event_registry.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_io.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_server.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_client_list.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_roots.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_cfg.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_stats_view.cpp
	${ROOT_PATH}/src/ds/app/engine/unique_id.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_settings.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_data.cpp
	${ROOT_PATH}/src/ds/app/engine/engine.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_client.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_io_defs.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_standalone.cpp
	${ROOT_PATH}/src/ds/app/engine/engine_clientserver.cpp
	${ROOT_PATH}/src/ds/app/error.cpp
	${ROOT_PATH}/src/ds/app/blob_reader.cpp
	${ROOT_PATH}/src/ds/app/camera_utils.cpp
	${ROOT_PATH}/src/ds/app/app_defs.cpp
	${ROOT_PATH}/src/ds/app/auto_update.cpp
	${ROOT_PATH}/src/ds/app/blob_registry.cpp
	${ROOT_PATH}/src/ds/app/app.cpp
	${ROOT_PATH}/src/ds/app/image_registry.cpp
	${ROOT_PATH}/src/ds/app/environment.cpp
	${ROOT_PATH}/src/ds/app/event.cpp
	${ROOT_PATH}/src/ds/app/auto_draw.cpp
	${ROOT_PATH}/src/ds/app/event_notifier.cpp
	${ROOT_PATH}/src/ds/app/auto_update_list.cpp
	${ROOT_PATH}/src/ds/ui/touch/button_behaviour.cpp
	${ROOT_PATH}/src/ds/ui/touch/picking.cpp
	${ROOT_PATH}/src/ds/ui/touch/momentum.cpp
	${ROOT_PATH}/src/ds/ui/touch/touch_process.cpp
	${ROOT_PATH}/src/ds/ui/touch/multi_touch_constraints.cpp
	${ROOT_PATH}/src/ds/ui/touch/draw_touch_view.cpp
	${ROOT_PATH}/src/ds/ui/touch/touch_manager.cpp
	${ROOT_PATH}/src/ds/ui/touch/rotation_translator.cpp
	${ROOT_PATH}/src/ds/ui/touch/select_picking.cpp
	${ROOT_PATH}/src/ds/ui/touch/touch_translator.cpp
	${ROOT_PATH}/src/ds/ui/touch/touch_mode.cpp
	${ROOT_PATH}/src/ds/ui/tween/tweenline.cpp
	${ROOT_PATH}/src/ds/ui/tween/sprite_anim.cpp
	${ROOT_PATH}/src/ds/ui/service/glsl_image_service.cpp
	${ROOT_PATH}/src/ds/ui/service/pango_font_service.cpp
	${ROOT_PATH}/src/ds/ui/service/load_image_service.cpp
	${ROOT_PATH}/src/ds/ui/sprite/util/blend.cpp
	${ROOT_PATH}/src/ds/ui/sprite/util/clip_plane.cpp
	${ROOT_PATH}/src/ds/ui/sprite/sprite_engine.cpp
	${ROOT_PATH}/src/ds/ui/sprite/border.cpp
	${ROOT_PATH}/src/ds/ui/sprite/sprite.cpp
	${ROOT_PATH}/src/ds/ui/sprite/image.cpp
	${ROOT_PATH}/src/ds/ui/sprite/dirty_state.cpp
	${ROOT_PATH}/src/ds/ui/sprite/circle.cpp
	${ROOT_PATH}/src/ds/ui/sprite/shader/sprite_shader.cpp
	${ROOT_PATH}/src/ds/ui/sprite/gradient_sprite.cpp
	${ROOT_PATH}/src/ds/ui/sprite/mesh.cpp
	${ROOT_PATH}/src/ds/ui/sprite/nine_patch.cpp
	${ROOT_PATH}/src/ds/ui/sprite/text.cpp
	${ROOT_PATH}/src/ds/ui/sprite/image_with_thumbnail.cpp
	${ROOT_PATH}/src/ds/ui/sprite/circle_border.cpp
	${ROOT_PATH}/src/ds/ui/sprite/text_defs.cpp
	${ROOT_PATH}/src/ds/ui/ip/functions/ip_circle_mask.cpp
	${ROOT_PATH}/src/ds/ui/ip/ip_function.cpp
	${ROOT_PATH}/src/ds/ui/ip/ip_defs.cpp
	${ROOT_PATH}/src/ds/ui/ip/ip_function_list.cpp
	${ROOT_PATH}/src/ds/ui/image_source/image_client.cpp
	${ROOT_PATH}/src/ds/ui/image_source/image_glsl.cpp
	${ROOT_PATH}/src/ds/ui/image_source/image_drop_shadow.cpp
	${ROOT_PATH}/src/ds/ui/image_source/image_generator.cpp
	${ROOT_PATH}/src/ds/ui/image_source/image_source.cpp
	${ROOT_PATH}/src/ds/ui/image_source/image_owner.cpp
	${ROOT_PATH}/src/ds/ui/image_source/image_file.cpp
	${ROOT_PATH}/src/ds/ui/image_source/image_resource.cpp
	${ROOT_PATH}/src/ds/ui/image_source/image_arc.cpp
	${ROOT_PATH}/src/ds/ui/mesh_source/mesh_owner.cpp
	${ROOT_PATH}/src/ds/ui/mesh_source/mesh_source.cpp
	${ROOT_PATH}/src/ds/ui/mesh_source/mesh_cache_service.cpp
	${ROOT_PATH}/src/ds/ui/mesh_source/mesh_file_loader.cpp
	${ROOT_PATH}/src/ds/ui/mesh_source/mesh_sphere.cpp
	${ROOT_PATH}/src/ds/ui/mesh_source/mesh_file.cpp
	${ROOT_PATH}/src/ds/ui/layout/layout_sprite.cpp
	${ROOT_PATH}/src/ds/params/draw_params.cpp
	${ROOT_PATH}/src/ds/params/camera_params.cpp
	${ROOT_PATH}/src/ds/params/update_params.cpp
	${ROOT_PATH}/src/ds/debug/computer_info.cpp
	${ROOT_PATH}/src/ds/debug/debug_defines.cpp
	${ROOT_PATH}/src/ds/debug/logger.cpp
	${ROOT_PATH}/src/ds/math/math_func.cpp
	${ROOT_PATH}/src/ds/cfg/cfg_nine_patch.cpp
	${ROOT_PATH}/src/ds/cfg/settings.cpp
	${ROOT_PATH}/src/ds/cfg/cfg_text.cpp
	${ROOT_PATH}/src/ds/data/tuio_object.cpp
	${ROOT_PATH}/src/ds/data/resource_list.cpp
	${ROOT_PATH}/src/ds/data/key_value_store.cpp
	${ROOT_PATH}/src/ds/data/data_buffer.cpp
	${ROOT_PATH}/src/ds/data/read_write_buffer.cpp
	${ROOT_PATH}/src/ds/data/font_list.cpp
	${ROOT_PATH}/src/ds/data/color_list.cpp
	${ROOT_PATH}/src/ds/data/user_data.cpp
	${ROOT_PATH}/src/ds/data/resource.cpp

	${ROOT_PATH}/src/tuio/TuioClient.cpp
	${ROOT_PATH}/src/osc/OscBundle.cpp
	${ROOT_PATH}/src/osc/OscListener.cpp
	${ROOT_PATH}/src/osc/OscMessage.cpp
	${ROOT_PATH}/src/osc/OscSender.cpp
	${ROOT_PATH}/src/osc/ip/IpEndpointName.cpp
	${ROOT_PATH}/src/osc/ip/posix/NetworkingUtils.cpp
	${ROOT_PATH}/src/osc/ip/posix/UdpSocket.cpp
	${ROOT_PATH}/src/osc/osc/OscOutboundPacketStream.cpp
	${ROOT_PATH}/src/osc/osc/OscPrintReceivedElements.cpp
	${ROOT_PATH}/src/osc/osc/OscReceivedElements.cpp
	${ROOT_PATH}/src/osc/osc/OscTypes.cpp
	
)
